#!/bin/bash
# Familyhub OS - Kiosk Mode Setup Script
# Configures Raspberry Pi to auto-start Chromium in kiosk mode

set -e

echo "🖥️  Familyhub Kiosk Mode Setup"
echo "==============================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Check if running on Raspberry Pi
if [ ! -f /etc/rpi-issue ]; then
    echo -e "${YELLOW}Warning: This script is designed for Raspberry Pi${NC}"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

echo -e "${YELLOW}📦 Installing desktop and browser packages...${NC}"
sudo apt-get update
sudo apt-get install -y --no-install-recommends \
    xserver-xorg \
    x11-xserver-utils \
    xinit \
    openbox \
    chromium-browser \
    unclutter

echo ""
echo -e "${YELLOW}⚙️  Configuring auto-login to desktop...${NC}"
sudo raspi-config nonint do_boot_behaviour B4

echo ""
echo -e "${YELLOW}📝 Creating autostart configuration...${NC}"
mkdir -p ~/.config/openbox

cat > ~/.config/openbox/autostart << 'EOF'
# Familyhub Kiosk Mode Autostart
# Generated by setup-kiosk.sh

# Disable screen power management
xset s off
xset s noblank
xset -dpms

# Hide mouse cursor after 5 seconds of idle
unclutter -idle 5 -root &

# Wait for network and server to be ready
sleep 10

# Start Chromium in kiosk mode
chromium-browser \
    --noerrdialogs \
    --disable-infobars \
    --disable-session-crashed-bubble \
    --disable-restore-session-state \
    --kiosk \
    --incognito \
    --check-for-update-interval=31536000 \
    http://localhost &
EOF

echo ""
echo -e "${YELLOW}📝 Creating .xinitrc...${NC}"
cat > ~/.xinitrc << 'EOF'
#!/bin/sh
exec openbox-session
EOF
chmod +x ~/.xinitrc

# Create bash profile to auto-start X
echo ""
echo -e "${YELLOW}📝 Configuring auto-start X on login...${NC}"
if ! grep -q "startx" ~/.bash_profile 2>/dev/null; then
    cat >> ~/.bash_profile << 'EOF'

# Auto-start X server on tty1
if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
    startx -- -nocursor
fi
EOF
fi

echo ""
echo -e "${GREEN}════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✅ Kiosk mode configured successfully!${NC}"
echo -e "${GREEN}════════════════════════════════════════════════${NC}"
echo ""
echo "On next reboot, Chromium will automatically open"
echo "in full-screen mode displaying Familyhub."
echo ""
echo "📋 Useful commands:"
echo "   sudo systemctl status display-manager  # Check display status"
echo "   DISPLAY=:0 xdotool key F5              # Refresh browser"
echo ""
read -p "Reboot now? (y/N) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    sudo reboot
fi
